# Config for Dependabot updates.
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for NPM packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
