# Generated by Django 4.1.5 on 2023-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The full name (for example, ‘Manchester Open 2023’)",
                max_length=80,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="slug",
            field=models.SlugField(
                help_text="The end part of the URL (for example, ‘mancopen2023’)",
                max_length=16,
                verbose_name="URL slug",
            ),
        ),
    ]
