"""
Django settings for abacus project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from .base import *  # noqa

# General

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = "django-insecure-*&_h#(l^09u-+jl8u@8#q99pzy+ux)9n@dmgz&6sqdf11pl&8s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = True

# https://docs.djangoproject.com/en/dev/ref/settings/#allowed-hosts
ALLOWED_HOSTS: list[str] = ["localhost", "0.0.0.0", "127.0.0.1"]

# Caching

# https://docs.djangoproject.com/en/dev/ref/settings/#caches
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "",
    }
}
